version: "3"
services:
  nginx:
    container_name: nginx
    environment:
      NGINX_PORT: "80"
    # ports:
    #   - "80:80"
    volumes:
      - /etc/nginx/sites-available/default.conf:/etc/nginx/conf.d/default.conf:rw
  node-app:
    build:
      context: .
      args: 
        NODE_ENV: production
    # networks:
    #   - nginx-proxy
    environment:
      - NODE_ENV=development
      - SESSION_SECRET=secret
      - MSSQL_SA_PASSWORD=miepStrong(!)Password
      - MSSQL_USER=sa
    command: node index.js
  sql:
    container_name: sql
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      ACCEPT_EULA: 1
      MSSQL_SA_PASSWORD: miepStrong(!)Password
      MSSQL_USER: sa
      MSSQL_PID: Developer
# networks:
#   nginx-proxy:
#     driver: bridge

#  mongo: 
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
#      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}