version: "3"
services:
  nginx:
    ports:
      - "80:80"
  node-app:
    build:
      context: .
      args: 
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - SESSION_SECRET=${SESSION_SECRET}
    command: node index.js
  sql:
    container_name: sql
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      ACCEPT_EULA: 1
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      MSSQL_USER: ${MSSQL_USER}
      MSSQL_PID: Developer

#  mongo: 
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
#      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}