version: "3"
services:
  # nginx:
  #   container_name: nginx
  #   volumes:
  #     - /etc/nginx/sites-available/default.conf:/etc/nginx/conf.d/default.conf:rw
  frontend:
    container_name: frontend
    image: amandajkofoed/innocloud3
    ports:
      - "3000:3000"
  node-app:
    build:
      context: .
      args: 
        NODE_ENV: production
    volumes:
      - ./:/app #syncs data within the container from local 
      - /app/node_modules #anonymous volume
    environment:
      - NODE_ENV=production
      - MSSQL_HOST=${MSSQL_HOST}
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_USER=${MSSQL_USER}
      - SECRET_KEY=${SECRET_KEY}
      - AUTH_KEY=${AUTH_KEY}
      - DATA_TABLE_NAME=${DATA_TABLE_NAME}
    command: node index.js
  sql:
    container_name: sql
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_USER=${MSSQL_USER}
      - MSSQL_PID=Developer