version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build: .
    environment:
      - PORT=3000
    depends_on:
      - mongo
#  sql-server-db:
#    container_name: sql-server-db
#    image: mcr.microsoft.com/azure-sql-edge
#    environment:
#      PORT: 57000
#      ACCEPT_EULA: 1
#      MSSQL_SA_PASSWORD: miepStrong(!)Password
#      MSSQL_USER: SA
#      MSSQL_PID: Developer
  mongo: 
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mie
      - MONGO_INITDB_ROOT_PASSWORD=miepassword
    volumes:
      - mongo-db:/data/db 
  redis: 
    image: redis

volumes:
#  sql-server-db:
  mongo-db: