version: "3"
services:
  frontend:
    container_name: frontend
    image: amandajkofoed/innocloud3
    ports:
      - "3000:3000"
  node-app:
    build:
      context: .
      args: 
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - SERVER_NAME=${SERVER_NAME}
      - DATABASE_NAME=${DATABASE_NAME}
      - MSSQL_HOST=${MSSQL_HOST}
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_USER=${MSSQL_USER}
      - SECRET_KEY=${SECRET_KEY}
      - AUTH_KEY=${AUTH_KEY}
      - DATA_TABLE_NAME=${DATA_TABLE_NAME}
    command: node index.js
    depends_on:
      - sql
  sql:
    container_name: sql
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_USER=${MSSQL_USER}
      - MSSQL_PID=Developer
    volumes:
      - sqlvolume:/var/opt/mssql

volumes:
  sqlvolume: