version: "3"
services:
  nginx:
    ports:
      - "80:80"
    volumes:
      - /etc/nginx/sites-available/default.conf:/etc/nginx/conf.d/default.conf:rw
  node-app:
    build:
      context: .
      args: 
        NODE_ENV: production
    dns:
      - 130.226.1.2
    environment:
      - NODE_ENV=development
      - SESSION_SECRET=secret
      - MSSQL_SA_PASSWORD=miepStrong(!)Password
      - MSSQL_USER=sa
    command: node index.js
  sql:
    container_name: sql
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      ACCEPT_EULA: 1
      MSSQL_SA_PASSWORD: miepStrong(!)Password
      MSSQL_USER: sa
      MSSQL_PID: Developer

#  mongo: 
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
#      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}